### ISSUE TITLE
Webpack dependecy + unexplained error

### ISSUE THREAD

**Issue by N0wan** [gadhagod/vscode-chrome-extension-devtools#3]
Hi! Thx for creating this.

I encouter 2 errors that prevents me to use your extention.

1° The first one is a popup when trying to use the create command : 
"La commande 'Chrome Extension: Create New' a entraîné une erreur (Running the contributed command: 'chrome-extension-developer-tools.create' failed.)"

2° When trying to use Build or Watch commands, I'm asked to install Webpack globally (which is done already).
Which is the Webpack version that is needed ?
I'm on Windows 10, and I remember that for some other extensions (I remember of Babel), I had to hard-specify some paths to my profile for the extension to be able to find its dependencies.

Are you using some config parameters ?

**Comment by gadhagod** [comment]
Hello @N0wan. Many thanks for bringing this to my attention.

For your first problem, I have a few questions to better understand the bug. When does this error occur? Does it happen right when you execute the command or after clicking "create" on the "new extension" page. Can you please open your developer tools and let let me know any relevant errors that show up?
![Screen Shot 2021-09-26 at 3 25 38 PM](https://user-images.githubusercontent.com/69025547/134826170-3ef46de9-5496-489d-aa42-e51b9d2f66ea.png) 

As for your second, type the build and create commands simply run webpack commands in the VSCode terminal. Try typing "webpack" into your terminal. `npm i -g webpack` should allow you to run this command from terminal. Let me know if this doesn't work. (NOTE: until then you can simply type these commands: 
1. `webpack --mode=production --config config/webpack.config.js` for build
2. `webpack --mode=development --watch --config config/webpack.config.js` for watch

Again, thanks for reporting this. I'll get started on a fix as soon as I determine the cause of these errors.

**Comment by GavG** [comment]
Same issue here on Ubuntu 21.04. Executing the chrome-extension-developer-tools.create command yields the aforementioned error message and a blank view titled 'New Chrome Extension':

![image](https://user-images.githubusercontent.com/25467741/140162333-34f45af1-0d2d-4ae4-8082-de64178572b6.png)

Nothing appears in the logs when this happen, have checked with verbose log level.
Haven't tried in a fresh vscode instance yet so can't rule out that it doesn't have anything to do with the other extensions installed.

**Comment by gadhagod** [comment]
Thanks for the additional @GavG. I see in your chrome inspect window that there is one error present.
![Screen Shot 2021-11-03 at 7 22 12 PM](https://user-images.githubusercontent.com/69025547/140247015-f7e07cfa-19a4-4796-acf0-bc8e883b3e26.png)
Is the error shown relevant to this extension?

**Comment by GavG** [comment]
Hi gadhagod,

The one error I do have in the console is from vscode, a deprecation notice, occurs even with all extensions disabled, I believe this is an onging issue: https://github.com/microsoft/vscode/issues/82524 and shouldn't affect this extension.

Starting this extension in a workspace with all other extensions diabled raises a message as before when invoking create new: 
![image](https://user-images.githubusercontent.com/25467741/140612673-19157b68-0b62-423c-9431-8b71d08c4908.png)

However it has now started displaying more info, it seems it can't find a file in the src directory. I notice that thie src directory is excludded by the src/** directive in the .vscodeignore file, is this intentional?

**Comment by GavG** [comment]
Copying the src directory from this repo over to my local extension seems to solve the issue: 
![image](https://user-images.githubusercontent.com/25467741/140613164-08dd3534-f989-40d1-9942-08319d1897a2.png)

**Comment by gadhagod** [comment]
Hey @GavG.
Thanks for the incredibly valuable info! I believe https://github.com/gadhagod/vscode-chrome-extension-devtools/commit/2c0665e7c8afa64c4d25e2dae774cd360a028b24 should fix this. I'll publish a new release once I absolutely confirm this.

It seems that when the extension is published, the typescript is built and put into the `out` directory. The `src` directory is ignored in this process. I moved the `webviews` directory out of `src` and into the root so that the HTML files in them could be referenced.

**Comment by gadhagod** [comment]
Release 2.0.0 should fix this bug.
